name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
    id-token: write
    contents: read

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # login to Azure
      - uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build project
        uses: ./.github/workflows/build.yaml

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEB_APP_NAME}}
          package: ./publish

      - name: logout
        run: az logout

      
# - name: Checkout code
      #   uses: actions/checkout@main

      # - name: Set up .NET Core
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }} # Adjust the version as needed

      # - name: Restore dependencies
      #   run: dotnet restore
      #   working-directory: src

      # - name: Build
      #   run: dotnet build --configuration Release --no-restore
      #   working-directory: src

      # - name: Run tests
      #   run: dotnet test --no-restore --verbosity normal
      #   working-directory: src

      # - name: Publish
      #   run: dotnet publish --no-restore --configuration Release --output ./publish
      #   working-directory: src